### ISSUE TITLE
Subscriptions: Crate product history

### ISSUE THREAD

**Issue by cameronRomo** [ETBassist/Crate#38]
As a user in profile view,
* I'd like to see a history of products that have been delivered and what was kept

**Comment by lo-la-do-li** [comment]
@cameronRomo, What do you think? 

1. Should user be able to access all order history from the profile page (including all crates subscribed to) 
2. Or from each individual crate subscription in the "Subscriptions" view? (e.g., a button that says "View Order History")

**Comment by cameronRomo** [comment]
@lo-la-do-li , that's a great question!
Seeing as there can be multiple subscriptions, I'm inclined to go with option 2. What are your thoughts??

**Comment by lo-la-do-li** [comment]
I agree - we can add an OrderHistory component(/page) and reuse the Grid component in the ui folder, passing in the products from each crate subscribed to

**Comment by cameronRomo** [comment]
I love the sound of that! Putting it on its own page in combination with using the `Grid` component sounds efficient and more intuitive. Alternatively, I think if it were to display both the user profile and subscription history on the same page -- it would quickly get over encumbered.

**Comment by lo-la-do-li** [comment]
Update on this issue - I was able to display the subscriptions as deliveries on the profile page using an action that is called in Subscriptions.js (getListByUser), located in modules/subscription/api/actions. We need to add logic to set each "deliveryDate" to every 30 days following the date the user initially subscribed, which is currently displayed by parsing "createdAt".
